"""Lightweight workflow-v1 schema metadata for YAML generators."""

from __future__ import annotations

from copy import deepcopy

WORKFLOW_SCHEMA_VERSION = "workflow-v1"

_WORKFLOW_V1_SCHEMA_DEFINITION: dict[str, object] = {
    "schema_version": {
        "type": "string",
        "required": True,
        "default": WORKFLOW_SCHEMA_VERSION,
        "allowed_values": [WORKFLOW_SCHEMA_VERSION],
        "role": "required_input",
        "description": "Workflow schema version.",
        "gui_visible": False,
    },
    "dataset.name": {
        "type": "string",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "optional_input",
        "description": "Dataset name used for metadata and default output directory.",
        "gui_visible": True,
    },
    "dataset.description": {
        "type": "string",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "optional_input",
        "description": "Human-readable dataset description.",
        "gui_visible": True,
    },
    "dataset.modality": {
        "type": "enum",
        "required": True,
        "default": "protein",
        "allowed_values": ["protein", "compound", "interaction"],
        "role": "required_input",
        "description": "Workflow modality.",
        "gui_visible": True,
    },
    "dataset.mode": {
        "type": "enum",
        "required": True,
        "default": "query_first",
        "allowed_values": ["query_first", "query_composition"],
        "role": "required_input",
        "description": "Workflow execution mode.",
        "gui_visible": True,
    },
    "dataset.interaction_type": {
        "type": "enum",
        "required": False,
        "default": None,
        "allowed_values": ["protein-protein", "protein-ligand"],
        "role": "optional_input",
        "description": "Interaction type required when dataset.modality is interaction.",
        "gui_visible": True,
    },
    "query.value": {
        "type": "string",
        "required": True,
        "default": None,
        "allowed_values": None,
        "role": "required_input",
        "description": "Executable query string.",
        "gui_visible": True,
    },
    "query.fields": {
        "type": "string_list",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "optional_input",
        "description": "Optional UniProt fields request parameter.",
        "gui_visible": True,
    },
    "query.crossref_fields": {
        "type": "string_list",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "optional_input",
        "description": "Optional cross-reference fields for supported enrichment paths.",
        "gui_visible": True,
    },
    "query.include_isoform": {
        "type": "boolean",
        "required": False,
        "default": False,
        "allowed_values": None,
        "role": "optional_input",
        "description": "Whether UniProt requests should include isoforms.",
        "gui_visible": True,
    },
    "query.builder": {
        "type": "mapping",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "preserved_metadata",
        "description": "Preserved GUI-oriented metadata. It does not affect execution.",
        "gui_visible": False,
    },
    "query.composition": {
        "type": "list",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "preserved_metadata",
        "description": "Preserved composition metadata. It must match query.value when present.",
        "gui_visible": False,
    },
    "execution.enrich": {
        "type": "boolean",
        "required": False,
        "default": True,
        "allowed_values": None,
        "role": "optional_input",
        "description": "Enable supported enrichment behavior.",
        "gui_visible": True,
    },
    "execution.max_workers": {
        "type": "integer",
        "required": False,
        "default": 5,
        "allowed_values": None,
        "role": "optional_input",
        "description": "Worker count for supported workflow and enrichment paths.",
        "gui_visible": True,
    },
    "execution.total_retries": {
        "type": "integer",
        "required": False,
        "default": 3,
        "allowed_values": None,
        "role": "optional_input",
        "description": "Retry count for supported interfaces.",
        "gui_visible": True,
    },
    "execution.chembl_pages_to_fetch": {
        "type": "integer",
        "required": False,
        "default": -1,
        "allowed_values": None,
        "role": "optional_input",
        "description": "ChEMBL page cap. Use -1 for all pages or a positive integer.",
        "gui_visible": True,
    },
    "execution.uniprot_timeout": {
        "type": "number",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "optional_input",
        "description": "Optional UniProt request timeout.",
        "gui_visible": True,
    },
    "execution.debug": {
        "type": "boolean",
        "required": False,
        "default": False,
        "allowed_values": None,
        "role": "optional_input",
        "description": "Enable debug logging.",
        "gui_visible": True,
    },
    "harmonization.id_column": {
        "type": "string",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "optional_input",
        "description": "Optional deterministic ID column for tabular exports.",
        "gui_visible": True,
    },
    "export.output_dir": {
        "type": "string",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "optional_input",
        "description": "Output directory.",
        "gui_visible": True,
    },
    "export.format": {
        "type": "enum",
        "required": False,
        "default": "csv",
        "allowed_values": ["csv", "json", "xml", "parquet"],
        "role": "optional_input",
        "description": "Output format.",
        "gui_visible": True,
    },
    "export.include_metadata": {
        "type": "boolean",
        "required": False,
        "default": True,
        "allowed_values": None,
        "role": "optional_input",
        "description": "Write metadata.json.",
        "gui_visible": True,
    },
    "export.include_summary": {
        "type": "boolean",
        "required": False,
        "default": True,
        "allowed_values": None,
        "role": "optional_input",
        "description": "Write run_summary.yml.",
        "gui_visible": True,
    },
    "export.manifest_file": {
        "type": "string",
        "required": False,
        "default": "metadata.json",
        "allowed_values": None,
        "role": "optional_input",
        "description": "Metadata manifest filename.",
        "gui_visible": True,
    },
    "export.summary_file": {
        "type": "string",
        "required": False,
        "default": "run_summary.yml",
        "allowed_values": None,
        "role": "optional_input",
        "description": "Run summary filename.",
        "gui_visible": True,
    },
    "resources.primary": {
        "type": "string_list",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "future_feature",
        "description": "Future resource-driven routing metadata.",
        "gui_visible": False,
    },
    "resources.integration": {
        "type": "string_list",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "future_feature",
        "description": "Future resource-driven integration metadata.",
        "gui_visible": False,
    },
    "export.result_files": {
        "type": "mapping",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "future_feature",
        "description": "Future user-defined output filename control.",
        "gui_visible": False,
    },
    "harmonization.unique_sequence_strategy": {
        "type": "string",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "future_feature",
        "description": "Future sequence deduplication strategy control.",
        "gui_visible": False,
    },
    "harmonization.metadata_fields": {
        "type": "string_list",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "future_feature",
        "description": "Future output metadata field selection control.",
        "gui_visible": False,
    },
    "interaction_retrieval": {
        "type": "mapping",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "future_feature",
        "description": "Future explicit PPI or PLI retrieval configuration.",
        "gui_visible": False,
    },
    "activity_retrieval": {
        "type": "mapping",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "future_feature",
        "description": "Future explicit activity retrieval configuration.",
        "gui_visible": False,
    },
    "chemical_metadata_integration": {
        "type": "mapping",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "future_feature",
        "description": "Future compound metadata integration configuration.",
        "gui_visible": False,
    },
    "protein_target_integration": {
        "type": "mapping",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "future_feature",
        "description": "Future protein target metadata integration configuration.",
        "gui_visible": False,
    },
    "temperature_enrichment": {
        "type": "mapping",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "future_feature",
        "description": "Future temperature metadata enrichment configuration.",
        "gui_visible": False,
    },
    "cross_source_integration": {
        "type": "mapping",
        "required": False,
        "default": None,
        "allowed_values": None,
        "role": "future_feature",
        "description": "Future cross-source integration rule configuration.",
        "gui_visible": False,
    },
}


def get_workflow_v1_schema_definition() -> dict[str, object]:
    """Return the workflow-v1 schema definition used by YAML generators."""
    return deepcopy(_WORKFLOW_V1_SCHEMA_DEFINITION)
