[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bioseqdownloader"
version = "0.1.0"
description = "Tool to download and integrate biological data from multiple APIs (UniProt, AlphaFold, BioGRID, KEGG, etc.)"
readme = "README.md"
authors = [{ name = "Kren AI Lab", email = "krenai@umag.cl" }]
requires-python = ">=3.10,<4.0"

classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
]

dependencies = [
    "pandas",
    "tqdm",
    "requests",
    "rcsb-api",
    "biopython",
    "zeep",
    "python-dotenv",
    "pyyaml",
    "beautifulsoup4",
    "typer",
    "gradio",
]

[project.scripts]
bioseq-dl = "bioseq_dl.cli.main:app"
bioseq-dl-init = "bioseq_dl.init_config:main_init"

[project.urls]
Homepage = "https://github.com/ProteinEngineering-PESB2/BioSeqDownloader"
Issues = "https://github.com/ProteinEngineering-PESB2/BioSeqDownloader/issues"

[tool.hatch.build.targets.wheel]
packages = ["bioseq_dl"]
