# More inputs can be added from
# https://biodbnet.abcc.ncifcrf.gov/webServices/rest.php/biodbnetRestApi.json?method=getinputs
inputs = [
    "ecnumber",
    "geneid",
    "genesymbol",
    "genesymbolandsynonyms",
    "genesymbolorderedlocus",
    "genesymbolorf",
    "goid",
    "interproid",
    "keggcompoundid",
    "keggcompoundname",
    "keggdiseaseid",
    "keggdrugid",
    "keggdrugname",
    "kegggeneid",
    "keggpathwayid",
    "pdbid",
    "pfamid",
    "pubchemid",
    "reactomepathwayname",
    "refseqgenomicaccession",
    "refseqmrnaaccession",
    "refseqproteinaccession",
    "taxonid",
    "uniprotaccession",
    "uniprotentryname",
    "uniprotproteinname",
]

outputs = [
    "affyid",
    "genesymbol",
    "go-biologicalprocess",
    # "affyid",
    # "agilentid",
    # "allergomecode",
    # "apldb_cryptodbid",
    # "biocartapathwayname",
    # "biocycid",
    # "ccdsid",
    # "chromosomallocation",
    # "cleanexid",
    # "codelinkid",
    # "cosmicid",
    # "cpdbproteininteractor",
    # "ctddiseaseinfo",
    # "ctddiseasename",
    # "cygdid",
    # "dbsnpid",
    # "dictybaseid",
    # "dipid",
    # "disprotid",
    # "drugbankdrugid",
    # "drugbankdruginfo",
    # "drugbankdrugname",
    # "echobaseid",
    # "ecogeneid",
    # "ensemblbiotype",
    # "ensemblgeneid",
    # "ensemblgeneinfo",
    # "ensemblproteinid",
    # "ensembltranscriptid",
    # "flybasegeneid",
    # "flybaseproteinid",
    # "flybasetranscriptid",
    # "gaddiseaseinfo",
    # "gaddiseasename",
    # "genbanknucleotideaccession",
    # "genbanknucleotidegi",
    # "genbankproteinaccession",
    # "genbankproteingi",
    # "geneid",
    # "geneinfo",
    # "genesymbol",
    # "genesymbolandsynonyms",
    # "genesymbolorderedlocus",
    # "genesymbolorf",
    # "genesynonyms",
    # "genefarmid",
    # "go-biologicalprocess",
    # "go-cellularcomponent",
    # "go-molecularfunction",
    # "goid",
    # "gseastandardname",
    # "h-invlocusid",
    # "hamapid",
    # "hgncid",
    # "hmdbmetabolite",
    # "homolog-allensgeneid",
    # "homolog-allensproteinid",
    # "homolog-allgeneid",
    # "homolog-humanensgeneid",
    # "homolog-humanensproteinid",
    # "homolog-humangeneid",
    # "homolog-mouseensgeneid",
    # "homolog-mouseensproteinid",
    # "homolog-mousegeneid",
    # "homolog-ratensgeneid",
    # "homolog-ratensproteinid",
    # "homolog-ratgeneid",
    # "homologeneid",
    # "hpaid",
    # "hprdid",
    # "hprdproteincomplex",
    # "hprdproteininteractor",
    # "illuminaid",
    # "imgt/gene-dbid",
    # "interproid",
    # "ipiid",
    # "keggdiseaseid",
    # "kegggeneid",
    # "keggorthologyid",
    # "keggpathwayid",
    # "keggpathwayinfo",
    # "keggpathwaytitle",
    # "legiolistid",
    # "lepromaid",
    # "locustag",
    # "maizegdbid",
    # "meropsid",
    # "mgc(zgc/xgc)id",  # noqa: ERA001
    # "mgc(zgc/xgc)imageid",  # noqa: ERA001
    # "mgc(zgc/xgc)info",  # noqa: ERA001
    # "mgiid",
    # "mimid",
    # "miminfo",
    # "mirbaseid",
    # "ncipidpathwayname",
    # "ncipidproteincomplex",
    # "ncipidproteininteractor",
    # "ncipidptm",
    # "orphanetid",
    # "pantherid",
    # "paralog-ensgeneid",
    # "pbrid",
    # "pdbid",
    # "peroxibaseid",
    # "pfamid",
    # "pharmgkbdruginfo",
    # "pharmgkbgeneid",
    # "pirid",
    # "pirsfid",
    # "pptasedbid",
    # "printsid",
    # "prodomid",
    # "prositeid",
    # "pseudocapid",
    # "pubmedid",
    # "reactomeid",
    # "reactomepathwayname",
    # "rebaseid",
    # "refseqgenomicaccession",
    # "refseqgenomicgi",
    # "refseqmrnaaccession",
    # "refseqncrnaaccession",
    # "refseqnucleotidegi",
    # "refseqproteinaccession",
    # "refseqproteingi",
    # "rfamid",
    # "rgdid",
    # "sgdid",
    # "smartid",
    # "stringproteininteractor",
    # "tairid",
    # "taxonid",
    # "tcdbid",
    # "tigrfamsid",
    # "tuberculistid",
    # "ucscid",
    # "unigeneid",
    # "uniprotaccession",
    # "uniprotentryname",
    # "uniprotinfo",
    # "uniprotproteinname",
    # "unistsid",
    # "vectorbasegeneid",
    # "vegageneid",
    # "vegaproteinid",
    # "vegatranscriptid",
    # "wormbasegeneid",
    # "wormpepproteinid",
    # "xenbasegeneid",
    # "zfinid"
]
