compound:
  id: chebi_accession
compounds:
  id: standardized_chebi_id
  ascii_name: data.ascii_name
  chebi_accession: data.chebi_accession
  formula: data.chemical_data.formula
  charge: data.chemical_data.charge
  mass: data.chemical_data.mass
  monoisotopic_mass: data.chemical_data.monoisotopic_mass
  species: data.compound_origins.species_text
  species_accession: data.compound_origins.species_accession
  component: data.compound_origins.component_text
  component_accession: data.compound_origins.component_accession
  strain: data.compound_origins.strain_text
  strain_accession: data.compound_origins.strain_accession
  source: data.compound_origins.source
  source_accession: data.compound_origins.source_accession
  comments: data.compound_origins.comments
  species_accession_url: data.compound_origins.species_accession_url
  source_accession_url: data.compound_origins.source_accession_url
  species_accession_prefix: data.compound_origins.species_accession_prefix
  created_by: data.created_by
  database_accessions: data.database_accessions
  structure_id: data.default_structure.id
  smiles: data.default_structure.smiles
  inchi: data.default_structure.standard_inchi
  inchikey: data.default_structure.standard_inchi_key
  wurcs: data.default_structure.wurcs
  is_r_group: data.default_structure.is_r_group
  definition: data.definition
  is_released: data.is_released
  modified_on: data.modified_on
  name: data.name
  names: data.names
  ontology_relations: data.ontology_relations
  roles_classification: data.roles_classification
  secondary_ids: data.secondary_ids
  stars: data.stars
es_search:
  index: _index
  type: _type
  id: _id
  score: _score
  chebi_accession: _source.chebi_accession
  name: _source.name
  ascii_name: _source.ascii_name
  stars: _source.stars
  default_structure: _source.default_structure
  definition: _source.definition
  formula: _source.formula
  monoisotopicmass: _source.monoisotopicmass
  inchikey: _source.inchikey
  inchi: _source.inchi
  smiles: _source.smiles
  charge: _source.charge
  mass: _source.mass
  structures: _source.structures
