activity:
  assay_id: assay_chembl_id
  type: type
  units: units
  value: value
substructure:
  atc_clasification: atc_classification
  availability_type: availability_type
  biotherapeutic: biotherapeutic
  black_box_warning: black_box_warning
  chemical_probe: chemical_probe
  chirality: chirality
  cross_references: cross_references
  dosed_ingredient: dosed_ingredient
  first_approval: first_approval
  first_in_class: first_in_class
  helm_notation: helm_notation
  inorganic_flag: inorganic_flag
  max_phase: max_phase
  molecule_chembl_id: molecule_chembl_id
  active_chembl_id: molecule_hierarchy.active_chembl_id
  molecule_chembl_id: molecule_hierarchy.molecule_chembl_id
  parent_chembl_id: molecule_hierarchy.parent_chembl_id
  properties_alogp: molecule_properties.alogp
  properties_aromatic_rings: molecule_properties.aromatic_rings
  properties_full_molformula: molecule_properties.full_molformula
  properties_full_mwt: molecule_properties.full_mwt
  properties_hba: molecule_properties.hba
  properties_hbd: molecule_properties.hbd
  properties_heavy_atoms: molecule_properties.heavy_atoms
  properties_mw_freebase: molecule_properties.mw_freebase
  properties_np_likeness_score: molecule_properties.np_likeness_score
  properties_num_ro5_violations: molecule_properties.num_ro5_violations
  properties_psa: molecule_properties.psa
  properties_qed_weighted: molecule_properties.qed_weighted
  properties_ro3_pass: molecule_properties.ro3_pass
  properties_rtb: molecule_properties.rtb
  canonical_smiles: molecule_structures.canonical_smiles
  molfile: molecule_structures.molfile
  standard_inchi: molecule_structures.standard_inchi
  standard_inchi_key: molecule_structures.standard_inchi_key
  molecule_type: molecule_type
  natural_product: natural_product
  oral: oral
  orphan: orphan
  parenteral: parenteral
  polymer_flag: polymer_flag
  pref_name: pref_name
  prodrug: prodrug
  structure_type: structure_type
  therapeutic_flag: therapeutic_flag
  topical: topical
  usan_stem: usan_stem
  usan_stem_definition: usan_stem_definition
  usan_substem: usan_substem
  usan_year: usan_year
  veterinary: veterinary
  withdrawn_flag: withdrawn_flag
molecule:
  atc_clasification: atc_classification
  availability_type: availability_type
  biotherapeutic: biotherapeutic
  black_box_warning: black_box_warning
  chemical_probe: chemical_probe
  chirality: chirality
  cross_references: cross_references
  dosed_ingredient: dosed_ingredient
  first_approval: first_approval
  first_in_class: first_in_class
  helm_notation: helm_notation
  inorganic_flag: inorganic_flag
  max_phase: max_phase
  molecule_chembl_id: molecule_chembl_id
  active_chembl_id: molecule_hierarchy.active_chembl_id
  molecule_chembl_id: molecule_hierarchy.molecule_chembl_id
  parent_chembl_id: molecule_hierarchy.parent_chembl_id
  properties_alogp: molecule_properties.alogp
  properties_aromatic_rings: molecule_properties.aromatic_rings
  properties_full_molformula: molecule_properties.full_molformula
  properties_full_mwt: molecule_properties.full_mwt
  properties_hba: molecule_properties.hba
  properties_hbd: molecule_properties.hbd
  properties_heavy_atoms: molecule_properties.heavy_atoms
  properties_mw_freebase: molecule_properties.mw_freebase
  properties_np_likeness_score: molecule_properties.np_likeness_score
  properties_num_ro5_violations: molecule_properties.num_ro5_violations
  properties_psa: molecule_properties.psa
  properties_qed_weighted: molecule_properties.qed_weighted
  properties_ro3_pass: molecule_properties.ro3_pass
  properties_rtb: molecule_properties.rtb
  canonical_smiles: molecule_structures.canonical_smiles
  molfile: molecule_structures.molfile
  standard_inchi: molecule_structures.standard_inchi
  standard_inchi_key: molecule_structures.standard_inchi_key
  molecule_type: molecule_type
  natural_product: natural_product
  oral: oral
  orphan: orphan
  parenteral: parenteral
  polymer_flag: polymer_flag
  pref_name: pref_name
  prodrug: prodrug
  structure_type: structure_type
  therapeutic_flag: therapeutic_flag
  topical: topical
  usan_stem: usan_stem
  usan_stem_definition: usan_stem_definition
  usan_substem: usan_substem
  usan_year: usan_year
  veterinary: veterinary
  withdrawn_flag: withdrawn_flag
assay:
  aidx: aidx
  assay_category: assay_category
  assay_cell_type: assay_cell_type
  assay_chembl_id: assay_chembl_id
  assay_classifications: assay_classifications
  assay_group: assay_group
  assay_organism: assay_organism
  assay_parameters: assay_parameters
  assay_strain: assay_strain
  assay_subcellular_fraction: assay_subcellular_fraction
  assay_tax_id: assay_tax_id
  assay_test_type: assay_test_type
  assay_tissue: assay_tissue
  assay_type: assay_type
  assay_type_description: assay_type_description
  bao_format: bao_format
  bao_label: bao_label
  cell_chembl_id: cell_chembl_id
  confidence_description: confidence_description
  confidence_score: confidence_score
  description: description
  document_chembl_id: document_chembl_id
  relationship_description: relationship_description
  relationship_type: relationship_type
  src_assay_id: src_assay_id
  src_id: src_id
  target_chembl_id: target_chembl_id
  tissue_chembl_id: tissue_chembl_id
  variant_sequence: variant_sequence
target:
  cross_references: cross_references
  organism: organism
  pref_name: pref_name
  score: score
  species_group_flag: species_group_flag
  target_chembl_id: target_chembl_id
  target_components: target_components
  target_type: target_type
  tax_id: tax_id