get:
  entry: ENTRY
  name: NAME
  class: CLASS
  path_map: PATHWAY_MAP
  ko_pathway: KO_PATHWAY
  rel_pathway: REL_PATHWAY
  description: DESCRIPTION
  symbol: SYMBOL
  orthology: ORTHOLOGY
  organism: ORGANISM
  pathway: PATHWAY
  network: NETWORK
  brite: BRITE
  motif: MOTIF
  dblinks: DBLINKS
  gene: GENE
  compound: COMPOUND
  reference: REFERENCE
pathways:
  pathway_id: PATHWAY_ID
  name: NAME
  description: DESCRIPTION
  class: CLASS
  pathway_map: PATHWAY_MAP
  network: NETWORK
  organism: ORGANISM
  gene: GENE
  compound: COMPOUND
  reference: REFERENCE
  rel_pathway: REL_PATHWAY
  ko_pathway: KO_PATHWAY
  drug: DRUG
  dblinkS: DBLINKS
  disease: DISEASE
  module: MODULE
