import xml.etree.ElementTree as ET
from typing import Any

import pandas as pd

# Code generated by ChatGPT, to make a fast implementation.

def dict_to_element(
    data: Any,
    parent: ET.Element,
    *,
    list_item_tag: str = "item"
) -> None:
    """
    Convierte dict / list / scalar a XML bajo `parent`.

    Reglas:
    - dict  -> <key>...</key>
    - list  -> <item>...</item> repetidos (configurable)
    - value -> texto del elemento
    """
    if isinstance(data, dict):
        for key, value in data.items():
            child = ET.SubElement(parent, key)
            dict_to_element(value, child, list_item_tag=list_item_tag)

    elif isinstance(data, list):
        for item in data:
            child = ET.SubElement(parent, list_item_tag)
            dict_to_element(item, child, list_item_tag=list_item_tag)

    else:
        parent.text = "" if data is None else str(data)


def dict_to_elementtree(
    data: dict,
    root_tag: str = "results",
    list_item_tag: str = "item",
) -> ET.ElementTree:
    root = ET.Element(root_tag)
    dict_to_element(data, root, list_item_tag=list_item_tag)
    return ET.ElementTree(root)


def elementtree_to_dataframe(
    tree: ET.ElementTree,
    record_path: str = "./item",
    list_item_tag: str = "item",
) -> pd.DataFrame:
    """
    Convert an ElementTree to a DataFrame.

    Rules:
    - Each element at record_path becomes one row
    - Leaf elements -> scalar values
    - Containers with repeated <item> -> list[str] or list[dict]
    """

    root = tree.getroot()
    records = root.findall(record_path)

    def is_leaf(el: ET.Element) -> bool:
        return len(list(el)) == 0

    def parse_container(el: ET.Element) -> Any:
        items = el.findall(f"./{list_item_tag}")

        # list container
        if items:
            # list[str]
            if all(is_leaf(it) for it in items):
                return [
                    (it.text or "").strip()
                    for it in items
                    if (it.text or "").strip()
                ]

            # list[dict]
            out = []
            for it in items:
                d = {}
                for c in list(it):
                    d[c.tag] = (c.text or "").strip() if is_leaf(c) else ET.tostring(c, encoding="unicode")
                out.append(d)
            return out

        # scalar or dict
        if is_leaf(el):
            return (el.text or "").strip()

        # dict (1 level)
        d = {}
        for c in list(el):
            d[c.tag] = (c.text or "").strip() if is_leaf(c) else ET.tostring(c, encoding="unicode")
        return d

    rows = []
    for rec in records:
        row: dict[str, Any] = {}
        for child in list(rec):
            if is_leaf(child):
                row[child.tag] = (child.text or "").strip()
            else:
                row[child.tag] = parse_container(child)

        # cast common numeric fields
        for k in ("length", "organism_id", "tax_id"):
            if k in row and isinstance(row[k], str) and row[k].isdigit():
                row[k] = int(row[k])

        rows.append(row)

    return pd.DataFrame(rows)